#!/bin/bash
#Author:Vinod Mali (vinodmali2007@gmail.com)
php -version > /dev/null 2>&1
if [ $? == 0 ]
then
echo "php is installed"
else
echo "php is not installed"
yum install -y php php-fpm php-mysql
fi
mysql -V > /dev/null 2>&1
if [ $? == 0 ]
then
echo "MySQL is installed"
else
echo "MySQL is not installed"
yum install -y mysql
fi
if [ -f /etc/init.d/nginx ]
then
echo "nginx is installed"
else
echo "nginx is not installed"
yum install -y nginx
fi
echo -n "Enter the domain name : "
read domain
echo "127.0.0.1 $domain" >> /etc/hosts
echo -n "Enter the document root for $domain : "
read doc_root
if [ ! -d $doc_root ]
then
mkdir -p $doc_root
fi
echo "
server {
    listen       80;
    server_name  $domain;

 location / {
        root   $doc_root;
        index  index.php;
    }

 location ~ \.php$ {
        root           $doc_root;
        fastcgi_pass   127.0.0.1:9000;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME  $doc_root\$fastcgi_script_name;
        include        fastcgi_params;
    }
}" > /etc/nginx/conf.d/$domain.conf

wget -P $doc_root http://wordpress.org/latest.zip
cd $doc_root
unzip latest.zip > /dev/null
cd wordpress
cp wp-config-sample.php wp-config.php
tput clear
echo -n "Enter database name : "
read db
echo -n "Enter database Username : "
read user
echo -n "Enter password for database user $dbuser : "
read pass
mysql -u root -e "create database $db"
mysql -u root -e "CREATE USER '$user'@'%' IDENTIFIED BY '$pass';"
mysql -u root -e "grant all privileges on $db.* to $user@localhost identified by '$pass' with grant option;"
mysql -u root -e "flush privileges;"
#sed -i '/DB_NAME/ s/database_name_here/"$db"/' $doc_root/wordpress/wp-config.php
#sed -i '/DB_USER/ s/username_here/"$user"/' $doc_root/wordpress/wp-config.php
#sed -i '/DB_PASSWORD/ s/password_here/"$pass"/' $doc_root/wordpress/wp-config.php
tput clear
d=`grep "DB_NAME" $doc_root/wordpress/wp-config.php`
replace "$d" "define('DB_NAME', '$db');" -- $doc_root/wordpress/wp-config.php
u=`grep "DB_USER" $doc_root/wordpress/wp-config.php`
replace "$u" "define('DB_USER', '$user');" -- $doc_root/wordpress/wp-config.php
p=`grep "DB_PASSWORD" $doc_root/wordpress/wp-config.php`
replace "$p" "define('DB_PASSWORD', '$pass');" -- $doc_root/wordpress/wp-config.php
tput clear
echo "Please browse the below url to install wordpress"
echo "$domain/wordpress"
/etc/init.d/nginx restart > /dev/null
